[workspace]
resolver = "2"
members = ["sandvox", "sandvox-xtask"]

#[profile.dev.package.sandvox]
#opt-level = 1

[patch.crates-io]
rodio = { git = "https://github.com/jgraef/rodio.git", branch = "switch/main" }
