# This file will be modified by the game. Any manual changes might be lost.

chunk_load_distance = 4
chunk_render_distance = 16

[graphics]
backends = ["VULKAN"]
power_preference = "none"
staging_chunk_size = 16384
memory_hints = "Performance"
vsync = false

[sound]
disabled = false
host = "default"
device = "default"
master_volume = 0.2

