[package]
name = "morton"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
morton-encoding = "2.0.1"

[[bench]]
name = "bench_against_morton_encoding"
harness = false
