[air]
# no texture
is_opaque = false

[dirt]
texture = "blocks/dirt.png"

[grass.texture]
bottom = "blocks/dirt.png"
top = "blocks/grass.png"
default = "blocks/dirt_grass_side.png"

[stone]
texture = "blocks/stone.png"

[sand]
texture = "blocks/sand.png"

[cobble]
texture = "blocks/cobble.png"
